In [4]:
import pandas as pd
import re
import json

In [5]:
path = "data"
bookdb = pd.read_csv(f"{path}/catalog.csv")

In [6]:
bookdb['available'] = 1

In [7]:
bookdb

,_id,title,author,average_rating,isbn,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,delete,available
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,439785960,eng,652,2095690,27591,9/16/2006,Scholastic Inc.,NaN,1
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,439358078,eng,870,2153167,29221,9/1/2004,Scholastic Inc.,NaN,1
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,439554896,eng,352,6333,244,11/1/2003,Scholastic,NaN,1
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,eng,435,2339585,36325,5/1/2004,Scholastic Inc.,NaN,1
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,439682584,eng,2690,41428,164,9/13/2004,Scholastic,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11122,45631,Expelled from Eden: A William T. Vollmann Reader,William T. Vollmann/Larry McCaffery/Michael He...,4.06,1560254416,eng,512,156,20,12/21/2004,Da Capo Press,NaN,1
11123,45633,You Bright and Risen Angels,William T. Vollmann,4.08,140110879,eng,635,783,56,12/1/1988,Penguin Books,NaN,1
11124,45634,The Ice-Shirt (Seven Dreams #1),William T. Vollmann,3.96,140131965,eng,415,820,95,8/1/1993,Penguin Books,NaN,1
11125,45639,Poor People,William T. Vollmann,3.72,60878827,eng,434,769,139,2/27/2007,Ecco,NaN,1
11126,45641,Las aventuras de Tom Sawyer,Mark Twain,3.91,8497646983,spa,272,113,12,5/28/2006,Edimat Libros,NaN,1

In [5]:
for i in bookdb.columns:
    print(i)
    print(bookdb[i].unique())

_id
[    1     2     4 ... 45634 45639 45641]
title
['Harry Potter and the Half-Blood Prince (Harry Potter  #6)'
 'Harry Potter and the Order of the Phoenix (Harry Potter  #5)'
 'Harry Potter and the Chamber of Secrets (Harry Potter  #2)' ...
 'The Ice-Shirt (Seven Dreams #1)' 'Poor People'
 'Las aventuras de Tom Sawyer']
author
['J.K. Rowling/Mary GrandPré' 'J.K. Rowling' 'W. Frederick Zimmerman' ...
 'C.S. Lewis/Ana Falcão Bastos'
 'C.S. Lewis/Pauline Baynes/Ana Falcão Bastos'
 'William T. Vollmann/Larry McCaffery/Michael Hemmingson']
average_rating
['4.57' '4.49' '4.42' '4.56' '4.78' '3.74' '4.73' '4.38' '4.22' '4.21'
 '3.44' '3.87' '4.07' '3.9' '3.83' '3.86' '3.91' '3.93' '4.59' '4.5'
 '4.36' '4.53' '3.84' '3.72' '4' '3.88' '4.33' '3.45' '3.76' '3.6' '4.06'
 '4.17' '3.55' '3.98' '4.13' '3.95' '4.24' '4.34' '3.92' '4.23' '3.75'
 '3.94' '3.77' '4.46' '3.68' '3.99' '3.25' '3.89' '3.82' '3.78' '4.01'
 '4.35' '4.28' '3.34' '3.67' '3.48' '3.5' '3.62' '4.27' '3.39' '4.12'
 '4.08' '4.05' '3.85' '2.99' '4.19' '3.71' '4.2' '3.65' '3.4' '4.11'
 '3.42' '4.02' '3.69' '4.1' '3.66' '4.61' '4.04' '3.97' '4.14' '3.57'
 '3.43' '3.22' '3.64' '3.96' '3.8' '3.81' '3.79' '3.23' '4.15' '4.39'
 '4.03' '3.73' '3.51' '3.63' '3.09' '3.59' '4.29' '0' '4.25' '4.26' '3.61'
 '4.16' '4.55' '4.52' '3.41' '4.7' '4.18' '3.58' '4.51' '3.15' '3.31'
 '4.09' '3.49' '3.56' '4.47' '4.44' '3.7' '4.32' '4.4' '4.31' '4.43' '2.8'
 '3.46' '2.83' '4.62' '2.67' '4.45' '4.3' '5' '3.1' '3.08' '3.27' '3.33'
 '3' '4.67' '4.63' '3.52' '3.36' '3.54' '3.17' '4.37' '3.29' '4.64' '3.38'
 '3.37' '3.16' '3.53' '2.88' '2.98' '3.35' '3.3' '3.24' '4.41' '4.48'
 '4.54' '4.6' '3.32' '3.13' '2' '3.2' '4.58' '2.82' '3.28' '2.62' '2.92'
 '3.47' '3.02' '1' ' Jr./Sam B. Warner' '3.14' '3.12' '3.18' '2.86' '3.26'
 '3.19' '3.03' '3.07' '3.11' '4.91' '2.55' '2.81' '4.75'
 ' one of the founding members of this Tolkien website)/Verlyn Flieger/Turgon (=David E. Smith)'
 '3.21' '4.71' '4.8' '2.72' '2.79' '2.96' '2.75' ' Rawles' '4.86' '4.65'
 '2.5' '4.82' '4.76' '4.72' '4.69' '1.67' '3.06' '2.94' '2.89' '3.04'
 '2.4' '2.61' ' Son & Ferguson' '2.77' '2.63' '4.88' '4.83' '2.93' '2.33']
isbn
['439785960' '439358078' '439554896' ... '140131965' '60878827'
 '8497646983']
language_code
['eng' 'en-US' 'fre' 'spa' 'en-GB' 'mul' 'grc' 'enm' 'en-CA' 'ger' 'jpn'
 'ara' 'nl' 'zho' 'lat' 'por' 'srp' '9.78E+12' 'ita' 'rus' 'msa' 'glg'
 'wel' 'swe' 'nor' 'tur' 'gla' 'ale']
num_pages
['652' '870' '352' '435' '2690' '152' '3342' '815' '215' '6' '544' '55'
 '256' '335' '304' '299' '254' '324' '270' '1728' '1184' '398' '1216'
 '218' '224' '558' '208' '48' '144' '56' '228' '137' '339' '369' '388'
 '14' '576' '334' '416' '248' '128' '288' '720' '448' '160' '81' '249'
 '138' '192' '108' '832' '123' '423' '436' '331' '592' '480' '426' '471'
 '291' '205' '240' '336' '386' '260' '384' '391' '864' '873' '206' '514'
 '838' '960' '837' '80' '803' '752' '360' '367' '320' '100' '216' '250'
 '32' '244' '191' '738' '287' '217' '154' '318' '348' '316' '506' '292'
 '797' '635' '91' '181' '178' '464' '102' '132' '311' '213' '245' '64'
 '272' '232' '147' '239' '528' '434' '439' '307' '298' '368' '72' '67'
 '347' '317' '827' '377' '1085' '547' '784' '773' '385' '776' '193' '227'
 '222' '238' '234' '1122' '231' '308' '203' '96' '179' '306' '145' '275'
 '104' '1075' '608' '211' '262' '88' '542' '828' '112' '397' '328' '532'
 '296' '456' '575' '419' '540' '408' '1392' '1168' '176' '105' '340' '681'
 '286' '571' '277' '826' '164' '118' '496' '533' '425' '363' '295' '1139'
 '418' '927' '499' '640' '438' '450' '381' '257' '259' '197' '200' '198'
 '274' '103' '182' '503' '497' '58' '95' '0' '736' '508' '18' '489' '467'
 '744' '585' '383' '258' '194' '4' '284' '5' '399' '269' '422' '1344'
 '201' '405' '432' '68' '392' '214' '338' '401' '400' '515' '458' '2'
 '512' '468' '452' '414' '721' '354' '168' '157' '125' '233' '716' '622'
 '613' '772' '653' '816' '710' '683' '574' '588' '1556' '462' '312' '541'
 '374' '161' '607' '136' '180' '1808' '1248' '289' '212' '142' '210' '148'
 '129' '172' '530' '554' '34' '221' '255' '264' '431' '282' '116' '69'
 '605' '672' '171' '188' '358' '127' '151' '420' '430' '223' '75' '390'
 '624' '577' '241' '376' '98' '226' '372' '267' '209' '664' '854' '159'
 '905' '302' '478' '559' '723' '584' '560' '524' '451' '440' '594' '345'
 '518' '207' '562' '519' '40' '196' '333' '476' '616' '495' '342' '449'
 '536' '389' '1064' '327' '409' '429' '848' '887' '928' '830' '407' '768'
 '276' '124' '364' '1076' '1199' '1016' '265' '379' '424' '1160' '859'
 '704' '1103' '3' '190' '230' '110' '460' '632' '529' '916' '751' '455'
 '729' '46' '294' '344' '1120' '162' '15' '303' '1328' '1137' '183' '502'
 '1680' '1438' '611' '671' '412' '445' '697' '25' '707' '156' '395' '150'
 '120' '326' '346' '380' '461' '441' '314' '902' '281' '732' '83' '165'
 '301' '323' '11' '199' '504' '1035' '713' '958' '465' '1254' '1327' '484'
 '261' '627' '763' '366' '404' '371' '619' '337' '373' '246' '204' '84'
 '266' '186' '313' '195' '187' '321' '77' '189' '111' '133' '482' '733'
 '808' '656' '1050' '361' '242' '29' '184' '73' '119' '396' '648' '140'
 '454' '319' '557' '437' '406' '673' '943' '1110' '896' '1104' '268' '225'
 '351' '341' '444' '370' '310' '74' '410' '8' '2088' '1059' '1878' '907'
 '220' '403' '1436' '1478' '1333' '247' '862' '243' '153' '511' '158'
 '394' '459' '940' '1023' '134' '618' '1456' '572' '891' '769' '563' '639'
 '155' '382' '278' '688' '106' '756' '143' '85' '349' '375' '174' '507'
 '597' '601' '691' '615' '849' '229' '641' '279' '493' '692' '483' '30'
 '650' '97' '490' '185' '800' '553' '817' '60' '520' '175' '166' '1088'
 '796' '70' '463' '914' '538' '1013' '16' '13' '475' '485' '931' '411'
 '596' '350' '522' '357' '603' '417' '546' '300' '1270' '78' '252' '94'
 '909' '24' '1347' '353' '535' '76' '743' '972' '509' '1227' '17' '1096'
 '427' '586' '86' '387' '1313' '167' '113' '675' '1136' '548' '647' '912'
 '253' '867' '696' '66' '280' '670' '543' '122' '135' '1200' '57' '481'
 '43' '251' '735' '1040' '170' '402' '1144' '305' '330' '964' '329' '89'
 '850' '10' '378' '453' '822' '356' '393' '359' '263' '895' '798' '355'
 '146' '343' '273' '219' '149' '9' '447' '474' '99' '1090' '235' '718'
 '293' '1054' '1276' '620' '1462' '1072' '590' '690' '169' '285' '636'
 '793' '290' '634' '728' '491' '126' '457' '12' '28' '442' '551' '479'
 '82' '21' '61' '36' '62' '130' '625' '573' '566' '325' '1008' '315' '685'
 '734' '39' '7' '309' '880' '606' '589' '51' '649' '237' '202' '498' '26'
 '517' '578' '79' '488' '820' '1176' '1192' '1074' '1487' '1838' '749'
 '726' '472' '469' '1007' '415' '556' '527' '1369' '362' '1296' '801'
 '666' '679' '283' '568' '581' '939' '709' '54' '35' '782' '271' '933'
 '761' '236' '513' '969' '44' '890' '1099' '644' '814' '980' '1443' '1180'
 '762' '628' '534' '537' '31' '766' '109' '600' '884' '1346' '428' '510'
 '297' '487' '999' '992' '580' '956' '659' '821' '1520' '693' '466' '687'
 '669' '332' '90' '567' '1207' '892' '655' '114' '92' '604' '49' '1036'
 '107' 'en-US' '565' '811' '1056' '711' '1092' '1107' '477' '667' '617'
 '715' '1012' '1' '492' '676' '1080' '1024' '1086' '505' '322' '71' '1084'
 '633' '1181' '760' '486' '748' '413' '421' '660' '177' '612' '646' '446'
 '579' '42' '780' '893' '555' '795' '740' '564' '684' '898' '626' '657'
 '1256' '1600' '1472' '774' '595' '1238' '365' '700' '602' '582' '722'
 '818' '812' '661' '569' '121' '701' '861' '727' '101' '500' '894' '703'
 '698' 'eng' '792' '869' '1003' '20' '501' '570' '746' '1840' '1046' '976'
 '1440' '1776' '521' '623' '645' '840' '1500' '1412' '1388' '1408' '443'
 '807' '1041' '1037' '677' '957' '433' '847' '834' '888' '63' '754' '470'
 '139' '552' '1757' '33' '654' '1312' '1258' '680' '1952' '750' '990'
 '1273' '1397' '131' '1504' '2198' '745' '609' '825' '786' '494' '1326'
 '549' '539' '473' '93' '674' '686' '593' '631' '755' '741' '2264' '1002'
 '1262' '1082' '1060' '1011' '163' '141' '777' '1260' '1480' '6576' '705'
 '658' '561' '778' '4736' '757' '1186' '1264' '3020' '841' '915' '886'
 '173' '852' '516' '50' '724' '758' '1132' '1020' '998' '610' '805' '614'
 '1083' '1379' '1212' '1376' '1162' '87' '997' '901' '550' '742' '630'
 '934' '2751' '1416' '59' '587' '1488' '1017' '1021' '725' '662' '65'
 '767' '1278' '1431' '525' '1222' '794' '583' '717' '806' '1232' '911'
 '936' '739' '598' '791' '788' '983' '966' '1536' '642' '1152' '1051'
 '531' '629' '37' '2021' '978' '835' '753' '702' '913' '1284' '115' '545'
 '836' '694' '1236' '1231' '868' '1042' '783' '638' '2480' '856' '3400'
 '712' '906' '789' '27' '944' '22']
ratings_count
[2095690 2153167    6333 ...   41236     396     783]
text_reviews_count
[27591 29221   244 ...   777  2148  1830]
publication_date
['9/16/2006' '9/1/2004' '11/1/2003' ... '5/31/1998' '7/10/1977'
 '10/11/2003']
publisher
['Scholastic Inc.' 'Scholastic' 'Nimble Books' ... 'Suma'
 'Panamericana Editorial' 'Editorial Presença']
delete
[nan 'Harvard University Press' 'Cold Spring Press'
 'Huntington House Publishers' 'Brown Son & Ferguson Ltd.']
available
[1]

In [6]:
bookdb.dtypes

_id                    int64
title                 object
author                object
average_rating        object
isbn                  object
language_code         object
num_pages             object
ratings_count          int64
text_reviews_count     int64
publication_date      object
publisher             object
delete                object
available              int64
dtype: object

In [7]:
bookdb = bookdb[bookdb["delete"].isna()]
bookdb.head()

,_id,title,author,average_rating,isbn,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,delete,available
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,439785960,eng,652,2095690,27591,9/16/2006,Scholastic Inc.,NaN,1
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,439358078,eng,870,2153167,29221,9/1/2004,Scholastic Inc.,NaN,1
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,439554896,eng,352,6333,244,11/1/2003,Scholastic,NaN,1
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,eng,435,2339585,36325,5/1/2004,Scholastic Inc.,NaN,1
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,439682584,eng,2690,41428,164,9/13/2004,Scholastic,NaN,1

In [8]:
bookdb = bookdb.drop("delete",axis=1)
bookdb.head()

,_id,title,author,average_rating,isbn,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,available
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,439785960,eng,652,2095690,27591,9/16/2006,Scholastic Inc.,1
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,439358078,eng,870,2153167,29221,9/1/2004,Scholastic Inc.,1
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,439554896,eng,352,6333,244,11/1/2003,Scholastic,1
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,eng,435,2339585,36325,5/1/2004,Scholastic Inc.,1
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,439682584,eng,2690,41428,164,9/13/2004,Scholastic,1

In [9]:
for i in bookdb.columns:
    print(i)
    print(bookdb[i].unique())

_id
[    1     2     4 ... 45634 45639 45641]
title
['Harry Potter and the Half-Blood Prince (Harry Potter  #6)'
 'Harry Potter and the Order of the Phoenix (Harry Potter  #5)'
 'Harry Potter and the Chamber of Secrets (Harry Potter  #2)' ...
 'The Ice-Shirt (Seven Dreams #1)' 'Poor People'
 'Las aventuras de Tom Sawyer']
author
['J.K. Rowling/Mary GrandPré' 'J.K. Rowling' 'W. Frederick Zimmerman' ...
 'C.S. Lewis/Ana Falcão Bastos'
 'C.S. Lewis/Pauline Baynes/Ana Falcão Bastos'
 'William T. Vollmann/Larry McCaffery/Michael Hemmingson']
average_rating
['4.57' '4.49' '4.42' '4.56' '4.78' '3.74' '4.73' '4.38' '4.22' '4.21'
 '3.44' '3.87' '4.07' '3.9' '3.83' '3.86' '3.91' '3.93' '4.59' '4.5'
 '4.36' '4.53' '3.84' '3.72' '4' '3.88' '4.33' '3.45' '3.76' '3.6' '4.06'
 '4.17' '3.55' '3.98' '4.13' '3.95' '4.24' '4.34' '3.92' '4.23' '3.75'
 '3.94' '3.77' '4.46' '3.68' '3.99' '3.25' '3.89' '3.82' '3.78' '4.01'
 '4.35' '4.28' '3.34' '3.67' '3.48' '3.5' '3.62' '4.27' '3.39' '4.12'
 '4.08' '4.05' '3.85' '2.99' '4.19' '3.71' '4.2' '3.65' '3.4' '4.11'
 '3.42' '4.02' '3.69' '4.1' '3.66' '4.61' '4.04' '3.97' '4.14' '3.57'
 '3.43' '3.22' '3.64' '3.96' '3.8' '3.81' '3.79' '3.23' '4.15' '4.39'
 '4.03' '3.73' '3.51' '3.63' '3.09' '3.59' '4.29' '0' '4.25' '4.26' '3.61'
 '4.16' '4.55' '4.52' '3.41' '4.7' '4.18' '3.58' '4.51' '3.15' '3.31'
 '4.09' '3.49' '3.56' '4.47' '4.44' '3.7' '4.32' '4.4' '4.31' '4.43' '2.8'
 '3.46' '2.83' '4.62' '2.67' '4.45' '4.3' '5' '3.1' '3.08' '3.27' '3.33'
 '3' '4.67' '4.63' '3.52' '3.36' '3.54' '3.17' '4.37' '3.29' '4.64' '3.38'
 '3.37' '3.16' '3.53' '2.88' '2.98' '3.35' '3.3' '3.24' '4.41' '4.48'
 '4.54' '4.6' '3.32' '3.13' '2' '3.2' '4.58' '2.82' '3.28' '2.62' '2.92'
 '3.47' '3.02' '1' '3.14' '3.12' '3.18' '2.86' '3.26' '3.19' '3.03' '3.07'
 '3.11' '4.91' '2.55' '2.81' '4.75' '3.21' '4.71' '4.8' '2.72' '2.79'
 '2.96' '2.75' '4.86' '4.65' '2.5' '4.82' '4.76' '4.72' '4.69' '1.67'
 '3.06' '2.94' '2.89' '3.04' '2.4' '2.61' '2.77' '2.63' '4.88' '4.83'
 '2.93' '2.33']
isbn
['439785960' '439358078' '439554896' ... '140131965' '60878827'
 '8497646983']
language_code
['eng' 'en-US' 'fre' 'spa' 'en-GB' 'mul' 'grc' 'enm' 'en-CA' 'ger' 'jpn'
 'ara' 'nl' 'zho' 'lat' 'por' 'srp' 'ita' 'rus' 'msa' 'glg' 'wel' 'swe'
 'nor' 'tur' 'gla' 'ale']
num_pages
['652' '870' '352' '435' '2690' '152' '3342' '815' '215' '6' '544' '55'
 '256' '335' '304' '299' '254' '324' '270' '1728' '1184' '398' '1216'
 '218' '224' '558' '208' '48' '144' '56' '228' '137' '339' '369' '388'
 '14' '576' '334' '416' '248' '128' '288' '720' '448' '160' '81' '249'
 '138' '192' '108' '832' '123' '423' '436' '331' '592' '480' '426' '471'
 '291' '205' '240' '336' '386' '260' '384' '391' '864' '873' '206' '514'
 '838' '960' '837' '80' '803' '752' '360' '367' '320' '100' '216' '250'
 '32' '244' '191' '738' '287' '217' '154' '318' '348' '316' '506' '292'
 '797' '635' '91' '181' '178' '464' '102' '132' '311' '213' '245' '64'
 '272' '232' '147' '239' '528' '434' '439' '307' '298' '368' '72' '67'
 '347' '317' '827' '377' '1085' '547' '784' '773' '385' '776' '193' '227'
 '222' '238' '234' '1122' '231' '308' '203' '96' '179' '306' '145' '275'
 '104' '1075' '608' '211' '262' '88' '542' '828' '112' '397' '328' '532'
 '296' '456' '575' '419' '540' '408' '1392' '1168' '176' '105' '340' '681'
 '286' '571' '277' '826' '164' '118' '496' '533' '425' '363' '295' '1139'
 '418' '927' '499' '640' '438' '450' '381' '257' '259' '197' '200' '198'
 '274' '103' '182' '503' '497' '58' '95' '0' '736' '508' '18' '489' '467'
 '744' '585' '383' '258' '194' '4' '284' '5' '399' '269' '422' '1344'
 '201' '405' '432' '68' '392' '214' '338' '401' '400' '515' '458' '2'
 '512' '468' '452' '414' '721' '354' '168' '157' '125' '233' '716' '622'
 '613' '772' '653' '816' '710' '683' '574' '588' '1556' '462' '312' '541'
 '374' '161' '607' '136' '180' '1808' '1248' '289' '212' '142' '210' '148'
 '129' '172' '530' '554' '34' '221' '255' '264' '431' '282' '116' '69'
 '605' '672' '171' '188' '358' '127' '151' '420' '430' '223' '75' '390'
 '624' '577' '241' '376' '98' '226' '372' '267' '209' '664' '854' '159'
 '905' '302' '478' '559' '723' '584' '560' '524' '451' '440' '594' '345'
 '518' '207' '562' '519' '40' '196' '333' '476' '616' '495' '342' '449'
 '536' '389' '1064' '327' '409' '429' '848' '887' '928' '830' '407' '768'
 '276' '124' '364' '1076' '1199' '1016' '265' '379' '424' '1160' '859'
 '704' '1103' '3' '190' '230' '110' '460' '632' '529' '916' '751' '455'
 '729' '46' '294' '344' '1120' '162' '15' '303' '1328' '1137' '183' '502'
 '1680' '1438' '611' '671' '412' '445' '697' '25' '707' '156' '395' '150'
 '120' '326' '346' '380' '461' '441' '314' '902' '281' '732' '83' '165'
 '301' '323' '11' '199' '504' '1035' '713' '958' '465' '1254' '1327' '484'
 '261' '627' '763' '366' '404' '371' '619' '337' '373' '246' '204' '84'
 '266' '186' '313' '195' '187' '321' '77' '189' '111' '133' '482' '733'
 '808' '656' '1050' '361' '242' '29' '184' '73' '119' '396' '648' '140'
 '454' '319' '557' '437' '406' '673' '943' '1110' '896' '1104' '268' '225'
 '351' '341' '444' '370' '310' '74' '410' '8' '2088' '1059' '1878' '907'
 '220' '403' '1436' '1478' '1333' '247' '862' '243' '153' '511' '158'
 '394' '459' '940' '1023' '134' '618' '1456' '572' '891' '769' '563' '639'
 '155' '382' '278' '688' '106' '756' '143' '85' '349' '375' '174' '507'
 '597' '601' '691' '615' '849' '229' '641' '279' '493' '692' '483' '30'
 '650' '97' '490' '185' '800' '553' '817' '60' '520' '175' '166' '1088'
 '796' '70' '463' '914' '538' '1013' '16' '13' '475' '485' '931' '411'
 '596' '350' '522' '357' '603' '417' '546' '300' '1270' '78' '252' '94'
 '909' '24' '1347' '353' '535' '76' '743' '972' '509' '1227' '17' '1096'
 '427' '586' '86' '387' '1313' '167' '113' '675' '1136' '548' '647' '912'
 '253' '867' '696' '66' '280' '670' '543' '122' '135' '1200' '57' '481'
 '43' '251' '735' '1040' '170' '402' '1144' '305' '330' '964' '329' '89'
 '850' '10' '378' '453' '822' '356' '393' '359' '263' '895' '798' '355'
 '146' '343' '273' '219' '149' '9' '447' '474' '99' '1090' '235' '718'
 '293' '1054' '1276' '620' '1462' '1072' '590' '690' '169' '285' '636'
 '793' '290' '634' '728' '491' '126' '457' '12' '28' '442' '551' '479'
 '82' '21' '61' '36' '62' '130' '625' '573' '566' '325' '1008' '315' '685'
 '734' '39' '7' '309' '880' '606' '589' '51' '649' '237' '202' '498' '26'
 '517' '578' '79' '488' '820' '1176' '1192' '1074' '1487' '1838' '749'
 '726' '472' '469' '1007' '415' '556' '527' '1369' '362' '1296' '801'
 '666' '679' '283' '568' '581' '939' '709' '54' '35' '782' '271' '933'
 '761' '236' '513' '969' '44' '890' '1099' '644' '814' '980' '1443' '1180'
 '762' '628' '534' '537' '31' '766' '109' '600' '884' '1346' '428' '510'
 '297' '487' '999' '992' '580' '956' '659' '821' '1520' '693' '466' '687'
 '669' '332' '90' '567' '1207' '892' '655' '114' '92' '604' '49' '1036'
 '107' '565' '811' '1056' '711' '1092' '1107' '477' '667' '617' '715'
 '1012' '1' '492' '676' '1080' '1024' '1086' '505' '322' '71' '1084' '633'
 '1181' '760' '486' '748' '413' '421' '660' '177' '612' '646' '446' '579'
 '42' '780' '893' '555' '795' '740' '564' '684' '898' '626' '657' '1256'
 '1600' '1472' '774' '595' '1238' '365' '700' '602' '582' '722' '818'
 '812' '661' '569' '121' '701' '861' '727' '101' '500' '894' '703' '698'
 '792' '869' '1003' '20' '501' '570' '746' '1840' '1046' '976' '1440'
 '1776' '521' '623' '645' '840' '1500' '1412' '1388' '1408' '443' '807'
 '1041' '1037' '677' '957' '433' '847' '834' '888' '63' '754' '470' '139'
 '552' '1757' '33' '654' '1312' '1258' '680' '1952' '750' '990' '1273'
 '1397' '131' '1504' '2198' '745' '609' '825' '786' '494' '1326' '549'
 '539' '473' '93' '674' '686' '593' '631' '755' '741' '2264' '1002' '1262'
 '1082' '1060' '1011' '163' '141' '777' '1260' '1480' '6576' '705' '658'
 '561' '778' '4736' '757' '1186' '1264' '3020' '841' '915' '886' '173'
 '852' '516' '50' '724' '758' '1132' '1020' '998' '610' '805' '614' '1083'
 '1379' '1212' '1376' '1162' '87' '997' '901' '550' '742' '630' '934'
 '2751' '1416' '59' '587' '1488' '1017' '1021' '725' '662' '65' '767'
 '1278' '1431' '525' '1222' '794' '583' '717' '806' '1232' '911' '936'
 '739' '598' '791' '788' '983' '966' '1536' '642' '1152' '1051' '531'
 '629' '37' '2021' '978' '835' '753' '702' '913' '1284' '115' '545' '836'
 '694' '1236' '1231' '868' '1042' '783' '638' '2480' '856' '3400' '712'
 '906' '789' '27' '944' '22']
ratings_count
[2095690 2153167    6333 ...   41236     396     783]
text_reviews_count
[27591 29221   244 ...   777  2148  1830]
publication_date
['9/16/2006' '9/1/2004' '11/1/2003' ... '5/31/1998' '7/10/1977'
 '10/11/2003']
publisher
['Scholastic Inc.' 'Scholastic' 'Nimble Books' ... 'Suma'
 'Panamericana Editorial' 'Editorial Presença']
available
[1]

In [10]:
bookdb.dtypes

_id                    int64
title                 object
author                object
average_rating        object
isbn                  object
language_code         object
num_pages             object
ratings_count          int64
text_reviews_count     int64
publication_date      object
publisher             object
available              int64
dtype: object

In [11]:
bookdb.to_csv(f"{path}/bookcleaningpart1.csv", index=False)

In [12]:
# testing accii II char recognition 
o="Le RÃ©seau Kinakuta (Cryptonomicon  #2)"
if(all(ord(c) < 128 for c in o)):
    print("valid")
else:
    print("invalid")
#re.match('[a-bA-B0-9@_!#$%^&*()<>?/\|}{~:;,_\-+\[\]]

invalid

In [13]:
bookdb = pd.read_csv(f"{path}/bookcleaningpart1.csv")

In [14]:
def asciiCheck(ser):
    listy = []
    for i in ser:
        listy.append(all(ord(c) < 128 for c in i))
    ser = pd.Series(listy, copy=False)
    return ser

In [15]:
bookdb = bookdb.reset_index(drop=True)
bookdb

,_id,title,author,average_rating,isbn,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,available
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,439785960,eng,652,2095690,27591,9/16/2006,Scholastic Inc.,1
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,439358078,eng,870,2153167,29221,9/1/2004,Scholastic Inc.,1
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,439554896,eng,352,6333,244,11/1/2003,Scholastic,1
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,eng,435,2339585,36325,5/1/2004,Scholastic Inc.,1
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,439682584,eng,2690,41428,164,9/13/2004,Scholastic,1
...,...,...,...,...,...,...,...,...,...,...,...,...
11118,45631,Expelled from Eden: A William T. Vollmann Reader,William T. Vollmann/Larry McCaffery/Michael He...,4.06,1560254416,eng,512,156,20,12/21/2004,Da Capo Press,1
11119,45633,You Bright and Risen Angels,William T. Vollmann,4.08,140110879,eng,635,783,56,12/1/1988,Penguin Books,1
11120,45634,The Ice-Shirt (Seven Dreams #1),William T. Vollmann,3.96,140131965,eng,415,820,95,8/1/1993,Penguin Books,1
11121,45639,Poor People,William T. Vollmann,3.72,60878827,eng,434,769,139,2/27/2007,Ecco,1
11122,45641,Las aventuras de Tom Sawyer,Mark Twain,3.91,8497646983,spa,272,113,12,5/28/2006,Edimat Libros,1

In [16]:
bookdb = bookdb[asciiCheck(bookdb["title"])].reset_index(drop=True)
bookdb = bookdb[asciiCheck(bookdb["author"])].reset_index(drop=True)
bookdb = bookdb[asciiCheck(bookdb["language_code"])].reset_index(drop=True)
bookdb = bookdb[asciiCheck(bookdb["publication_date"])].reset_index(drop=True)
bookdb = bookdb[asciiCheck(bookdb["publisher"])].reset_index(drop=True)

In [17]:
bookdb

,_id,title,author,average_rating,isbn,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,available
0,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,439554896,eng,352,6333,244,11/1/2003,Scholastic,1
1,9,"Unauthorized Harry Potter Book Seven News: ""Ha...",W. Frederick Zimmerman,3.74,976540606,en-US,152,19,1,4/26/2005,Nimble Books,1
2,10,Harry Potter Collection (Harry Potter #1-6),J.K. Rowling,4.73,439827604,eng,3342,28242,808,9/12/2005,Scholastic,1
3,12,The Ultimate Hitchhiker's Guide: Five Complete...,Douglas Adams,4.38,517226952,eng,815,3628,254,11/1/2005,Gramercy Books,1
4,13,The Ultimate Hitchhiker's Guide to the Galaxy ...,Douglas Adams,4.38,345453743,eng,815,249558,4080,4/30/2002,Del Rey Books,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10357,45631,Expelled from Eden: A William T. Vollmann Reader,William T. Vollmann/Larry McCaffery/Michael He...,4.06,1560254416,eng,512,156,20,12/21/2004,Da Capo Press,1
10358,45633,You Bright and Risen Angels,William T. Vollmann,4.08,140110879,eng,635,783,56,12/1/1988,Penguin Books,1
10359,45634,The Ice-Shirt (Seven Dreams #1),William T. Vollmann,3.96,140131965,eng,415,820,95,8/1/1993,Penguin Books,1
10360,45639,Poor People,William T. Vollmann,3.72,60878827,eng,434,769,139,2/27/2007,Ecco,1
10361,45641,Las aventuras de Tom Sawyer,Mark Twain,3.91,8497646983,spa,272,113,12,5/28/2006,Edimat Libros,1

In [18]:
bookdb.to_csv(f"{path}/bookcleaningpart2.csv", index=False)

In [19]:
jsonbook = bookdb.to_json(orient='records')

In [20]:
# fixed the json formatting problem by loading the json and dumping it
parsed = json.loads(jsonbook)
jsonfinal = json.dumps(parsed, indent=4)

In [21]:
with open(f"{path}/catalog.json",'w') as outfile:
    outfile.write(jsonfinal)